<a href="https://colab.research.google.com/github/DanKim115/component-library/blob/main/HW2_Python_basics_DanielKim.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


![logo](https://upload.wikimedia.org/wikipedia/commons/4/44/Huntsman-Wordmark-with-USU-Blue.gif#center)


---

# HW2- Python basics (20 pionts)

### Instructor: Pedram Jahangiry

Let's take a look at NumPy and Pandas now. We'll start with a few simple tasks, then we'll move on to more complicated questions.

**Important** Avoid running the cells directly above the example output shown, otherwise you will end up overwriting it

---

##### 1. Import Numpy package as np (0.5 point)

In [1]:
# CODE HERE
import numpy as np

#####  2. Create the following numpy array using two functions:  arange() and linspace(). You must generate the same answers. (2 points)

In [38]:
# Code here (using arange function)
array = np.arange(2, 20, 4)

formatted_result = ', '.join(map(str, array))

print(f"array([{formatted_result}])")

array([2, 6, 10, 14, 18])


In [ ]:
# Do NOT write here!


array([ 2,  6, 10, 14, 18])

In [42]:
# Code here (using linspace function)
array = np.linspace(2, 18, num=5)

# Format the output with commas
formatted_result = ', '.join(map(str, array))

# Print the formatted result
print(f"array([{formatted_result}])")

array([2.0, 6.0, 10.0, 14.0, 18.0])


In [ ]:
# Do NOT write here!


array([ 2.,  6., 10., 14., 18.])

##### 3. Create the following matrix of ones and save it as my_matrix. (1 point)

In [23]:
# Code here
my_matrix = np.ones((4,4))
print(my_matrix)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
# Do NOT write here


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 4. Reshape "my_matrix" into a new matrix as shown below. (1 point)

In [24]:
# Code here
my_matrix = np.reshape(my_matrix, (2, 8))

In [25]:
# Do NOT write here
my_matrix

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

#### 5. First, replace the first row of "my_matrix" with zeros. then replace the last column with 2s. Save the new matrix as "my_matrix2". (2 points)

In [26]:
# Code here
my_matrix = np.ones((4,4))
my_matrix[0, :] = 0
my_matrix[:, -1] = 2

my_matrix2 = my_matrix

In [27]:
# Do not write here
my_matrix2

array([[0., 0., 0., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.],
       [1., 1., 1., 2.]])

#### 6. Create the following matrix and save it as "A". (2 points)

In [31]:
# Code here
A = np.arange(0.01, 1.01, 0.01)

A = A.reshape(10, 10)

In [32]:
# Do NOT write here.
A

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

##### 7. Create a 10 * 10 matrix using random values drawn from a standard normal distribution. Call this matrix "B". Set seed number = 100 (2 points)

In [33]:
# Code here
# Set the random seed for reproducibility
np.random.seed(100)

# Create a 10x10 matrix with random values from a standard normal distribution
B = np.random.randn(10, 10)

In [34]:
# Do NOT write here
B

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079,
         0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081,
        -0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869,
         0.9370822 ,  0.73100034,  1.36155613, -0.32623806,  0.05567601],
       [ 0.22239961, -1.443217  , -0.75635231,  0.81645401,  0.75044476,
        -0.45594693,  1.18962227, -1.69061683, -1.35639905, -1.23243451],
       [-0.54443916, -0.66817174,  0.00731456, -0.61293874,  1.29974807,
        -1.73309562, -0.9833101 ,  0.35750775, -1.6135785 ,  1.47071387],
       [-1.1880176 , -0.54974619, -0.94004616, -0.82793236,  0.10886347,
         0.50780959, -0.86222735,  1.24946974, -0.07961125, -0.88973148],
       [-0.88179839,  0.01863895,  0.23784462,  0.01354855, -1.6355294 ,
        -1.04420988,  0.61303888,  0.73620521

##### 8. Multiply matrix A and B. (use the Matrix multiplication, NOT the element-wised multiplication) (1 point)

In [35]:
# Code here
C = A @ B
print(C)

[[-0.38520099  0.06358488 -0.05722663 -0.06955691  0.43190936 -0.12156679
   0.06534707  0.02587607 -0.11242174 -0.5925726 ]
 [-0.96896951  0.17349491 -0.17278352 -0.17456096  1.13265468 -0.2713685
   0.18147958  0.09578209 -0.42840209 -1.36081353]
 [-1.55273803  0.28340494 -0.28834041 -0.279565    1.8334     -0.4211702
   0.2976121   0.16568812 -0.74438244 -2.12905447]
 [-2.13650655  0.39331498 -0.40389731 -0.38456905  2.53414533 -0.57097191
   0.41374462  0.23559414 -1.06036278 -2.8972954 ]
 [-2.72027506  0.50322501 -0.5194542  -0.48957309  3.23489065 -0.72077361
   0.52987714  0.30550017 -1.37634313 -3.66553634]
 [-3.30404358  0.61313505 -0.63501109 -0.59457714  3.93563597 -0.87057532
   0.64600966  0.37540619 -1.69232348 -4.43377727]
 [-3.8878121   0.72304508 -0.75056798 -0.69958118  4.6363813  -1.02037702
   0.76214218  0.44531222 -2.00830382 -5.20201821]
 [-4.47158062  0.83295511 -0.86612487 -0.80458523  5.33712662 -1.17017873
   0.8782747   0.51521824 -2.32428417 -5.97025915]
 [

In [ ]:
# Do NOT write here


array([[-0.38520099,  0.06358488, -0.05722663, -0.06955691,  0.43190936,
        -0.12156679,  0.06534707,  0.02587607, -0.11242174, -0.5925726 ],
       [-0.96896951,  0.17349491, -0.17278352, -0.17456096,  1.13265468,
        -0.2713685 ,  0.18147958,  0.09578209, -0.42840209, -1.36081353],
       [-1.55273803,  0.28340494, -0.28834041, -0.279565  ,  1.8334    ,
        -0.4211702 ,  0.2976121 ,  0.16568812, -0.74438244, -2.12905447],
       [-2.13650655,  0.39331498, -0.40389731, -0.38456905,  2.53414533,
        -0.57097191,  0.41374462,  0.23559414, -1.06036278, -2.8972954 ],
       [-2.72027506,  0.50322501, -0.5194542 , -0.48957309,  3.23489065,
        -0.72077361,  0.52987714,  0.30550017, -1.37634313, -3.66553634],
       [-3.30404358,  0.61313505, -0.63501109, -0.59457714,  3.93563597,
        -0.87057532,  0.64600966,  0.37540619, -1.69232348, -4.43377727],
       [-3.8878121 ,  0.72304508, -0.75056798, -0.69958118,  4.6363813 ,
        -1.02037702,  0.76214218,  0.44531222

##### 9. Import Pandas package as pd (0.5 point)

In [43]:
# Code here
import pandas as pd

In [ ]:
# Do Not write here


##### 10. Create a data frame with three columns A, B, C. Name your data frame as df. Again use the seed number = 100
* Column A: 20 random numbers from the uniform distribution (2 point)
* Column B: the first 20 Capitals of english letters (3 points)
* Column C: range of numbers between 20 and 39 (1 point)


In [45]:
import string
# Code here
# Create Column A: 20 random numbers from the uniform distribution
column_a = np.random.uniform(low=0, high=100, size=20)

# Create Column B: the first 20 capitals of English letters
column_b = list(string.ascii_uppercase[:20])

# Create Column C: range of numbers between 20 and 39
column_c = np.arange(20, 40)

# Create the DataFrame
df = pd.DataFrame({
    'A': column_a,
    'B': column_b,
    'C': column_c
})


In [46]:
# Do Not write here
df

A  B   C
0   99.893227  A  20
1   58.269382  B  21
2   18.327900  C  22
3   38.684542  D  23
4   18.967353  E  24
5   41.077067  F  25
6   59.468007  G  26
7   71.658609  H  27
8   48.689148  I  28
9   30.958982  J  29
10  57.744137  K  30
11  44.170782  L  31
12  35.967810  M  32
13  32.133193  N  33
14  20.820724  O  34
15  45.125862  P  35
16  49.184291  Q  36
17  89.907631  R  37
18  72.936046  S  38
19  77.008977  T  39

##### 11. Create a new column in df and name is as "default". If A>0.5 then default =1 otherwise 0. (2 points)

In [47]:
# Code here
df['default'] = np.where(df['A'] > 0.5, 1, 0)

In [48]:
# Do Not write here
df

A  B   C  default
0   99.893227  A  20        1
1   58.269382  B  21        1
2   18.327900  C  22        1
3   38.684542  D  23        1
4   18.967353  E  24        1
5   41.077067  F  25        1
6   59.468007  G  26        1
7   71.658609  H  27        1
8   48.689148  I  28        1
9   30.958982  J  29        1
10  57.744137  K  30        1
11  44.170782  L  31        1
12  35.967810  M  32        1
13  32.133193  N  33        1
14  20.820724  O  34        1
15  45.125862  P  35        1
16  49.184291  Q  36        1
17  89.907631  R  37        1
18  72.936046  S  38        1
19  77.008977  T  39        1

# Good luck!